"""Coalestra public API."""

from collections.abc import Iterable, Mapping

from coalestra.adapters import (
    CallableBatchSource,
    CallableDerivedSource,
    CallableSource,
)
from coalestra.cache import (
    AsyncMemoryCache,
    CacheStats,
    PublishResult,
    PublishStatus,
    ResourcePublisher,
    ResourceUpdate,
)
from coalestra.concurrency import (
    CapacityController,
    CapacityLimiter,
    CapacitySnapshot,
)
from coalestra.core import (
    BUILDER_HEALTH_ASSESSMENT_SCHEMA,
    BUILDER_HEALTH_ASSESSMENT_SCHEMA_VERSION,
    BUILDER_HEALTH_SCHEMA,
    BUILDER_HEALTH_SCHEMA_VERSION,
    CASE_INSENSITIVE_KEY_NORMALIZER,
    COALESTRA_API_STABILITY,
    COALESTRA_CAPABILITIES_SCHEMA,
    COALESTRA_CAPABILITIES_SCHEMA_VERSION,
    ERROR_DIAGNOSTICS_SCHEMA,
    ERROR_DIAGNOSTICS_SCHEMA_VERSION,
    LEGACY_KEY_NORMALIZER,
    PRESERVE_KEY_NORMALIZER,
    AsyncCache,
    AtomicAsyncCache,
    AuthorityAwareCache,
    AuthorityPolicyProvider,
    AuthorityPolicyResolver,
    AuthorityResolver,
    BatchAsyncCache,
    BatchAtomicAsyncCache,
    BatchSizedSource,
    BatchSnapshotSource,
    BlockingSourceTimeoutConfigured,
    BuilderHealth,
    BuilderHealthAssessment,
    BuilderHealthAssessmentPolicy,
    BuilderHealthFinding,
    BuilderHealthReason,
    BuilderHealthSeverity,
    CacheLookup,
    CacheWriteResult,
    CacheWriteStatus,
    CapabilityRequirementError,
    CircuitOpenError,
    CoalestraCapabilities,
    CoalestraError,
    ConcurrencyLimitedSource,
    DependencyCycleError,
    DependencyResolutionError,
    DerivedSource,
    FetchContext,
    FreshnessPolicy,
    FreshnessPolicyProvider,
    KeyNormalizer,
    ObservabilityShutdownTimeoutError,
    ObservationPolicy,
    PayloadCopier,
    PayloadCopyHealth,
    PayloadCopyShutdownTimeoutError,
    PayloadCopySubsystemClosedError,
    PayloadIsolationError,
    PayloadIsolator,
    RefreshMode,
    ResilienceConfiguredSource,
    ResourceAcceptanceError,
    ResourceAcceptanceRule,
    ResourceKey,
    ResourceResolutionError,
    SerializedResourceError,
    SerializedSnapshotBuildError,
    SerializedSourceFailure,
    SessionClosedError,
    Snapshot,
    SnapshotAcceptanceError,
    SnapshotAcceptancePolicy,
    SnapshotAcceptanceReason,
    SnapshotAcceptanceViolation,
    SnapshotBuildError,
    SnapshotConsistencyError,
    SnapshotConsistencyPolicy,
    SnapshotDeadlineExceededError,
    SnapshotDiagnostics,
    SnapshotRequest,
    SnapshotRequirement,
    SnapshotSource,
    SnapshotValue,
    SourceAuthorityPolicy,
    SourceFailure,
    SourcePayload,
    SourceProtocolError,
    SourceQueueTimeoutError,
    SourceTimeoutError,
    SourceTimeoutGuarantee,
    SourceTimeoutGuaranteeStatus,
    SourceUnavailableError,
    SubmissionBacklogFullError,
    build_capabilities,
    deepcopy_payload,
    inspect_source_timeout_guarantee,
)
from coalestra.observability import (
    BufferedEventSink,
    BufferedMetricsSink,
    BufferedSinkStats,
    BufferOverflowPolicy,
    EventRecord,
    InMemoryMetrics,
    LoggingEventSink,
    MetricRecord,
    NullEventSink,
    NullMetrics,
)
from coalestra.orchestration import (
    PolicyResolver,
    SnapshotBuilder,
    SnapshotSession,
)
from coalestra.resilience import (
    CircuitBreaker,
    CircuitBreakerPolicy,
    CircuitIdentity,
    CircuitScope,
    CircuitSnapshot,
    CircuitState,
    ResiliencePolicyResolver,
    RetryPolicy,
    SourceResiliencePolicy,
)
from coalestra.sync import (
    SyncResourcePublisher,
    SyncSnapshotBuilder,
    SyncSnapshotSession,
)

__version__ = "0.6.1"


def capabilities() -> CoalestraCapabilities:
    """Return the immutable runtime compatibility contract for this installation."""

    return build_capabilities(__version__)


def require_capabilities(
    *,
    features: Iterable[str] = (),
    schemas: Mapping[str, int] | None = None,
) -> CoalestraCapabilities:
    """Validate integration requirements and return the installed capabilities."""

    installed = capabilities()
    installed.require(features=features, schemas=schemas)
    return installed


__all__ = [
    "BUILDER_HEALTH_ASSESSMENT_SCHEMA",
    "BUILDER_HEALTH_ASSESSMENT_SCHEMA_VERSION",
    "BUILDER_HEALTH_SCHEMA",
    "BUILDER_HEALTH_SCHEMA_VERSION",
    "CASE_INSENSITIVE_KEY_NORMALIZER",
    "COALESTRA_API_STABILITY",
    "COALESTRA_CAPABILITIES_SCHEMA",
    "COALESTRA_CAPABILITIES_SCHEMA_VERSION",
    "ERROR_DIAGNOSTICS_SCHEMA",
    "ERROR_DIAGNOSTICS_SCHEMA_VERSION",
    "LEGACY_KEY_NORMALIZER",
    "PRESERVE_KEY_NORMALIZER",
    "AsyncCache",
    "AsyncMemoryCache",
    "AtomicAsyncCache",
    "AuthorityAwareCache",
    "AuthorityPolicyProvider",
    "AuthorityPolicyResolver",
    "AuthorityResolver",
    "BatchAsyncCache",
    "BatchAtomicAsyncCache",
    "BatchSizedSource",
    "BatchSnapshotSource",
    "BlockingSourceTimeoutConfigured",
    "BufferOverflowPolicy",
    "BufferedEventSink",
    "BufferedMetricsSink",
    "BufferedSinkStats",
    "BuilderHealth",
    "BuilderHealthAssessment",
    "BuilderHealthAssessmentPolicy",
    "BuilderHealthFinding",
    "BuilderHealthReason",
    "BuilderHealthSeverity",
    "CacheLookup",
    "CacheStats",
    "CacheWriteResult",
    "CacheWriteStatus",
    "CallableBatchSource",
    "CallableDerivedSource",
    "CallableSource",
    "CapabilityRequirementError",
    "CapacityController",
    "CapacityLimiter",
    "CapacitySnapshot",
    "CircuitBreaker",
    "CircuitBreakerPolicy",
    "CircuitIdentity",
    "CircuitOpenError",
    "CircuitScope",
    "CircuitSnapshot",
    "CircuitState",
    "CoalestraCapabilities",
    "CoalestraError",
    "ConcurrencyLimitedSource",
    "DependencyCycleError",
    "DependencyResolutionError",
    "DerivedSource",
    "EventRecord",
    "FetchContext",
    "FreshnessPolicy",
    "FreshnessPolicyProvider",
    "InMemoryMetrics",
    "KeyNormalizer",
    "LoggingEventSink",
    "MetricRecord",
    "NullEventSink",
    "NullMetrics",
    "ObservabilityShutdownTimeoutError",
    "ObservationPolicy",
    "PayloadCopier",
    "PayloadCopyHealth",
    "PayloadCopyShutdownTimeoutError",
    "PayloadCopySubsystemClosedError",
    "PayloadIsolationError",
    "PayloadIsolator",
    "PolicyResolver",
    "PublishResult",
    "PublishStatus",
    "RefreshMode",
    "ResilienceConfiguredSource",
    "ResiliencePolicyResolver",
    "ResourceAcceptanceError",
    "ResourceAcceptanceRule",
    "ResourceKey",
    "ResourcePublisher",
    "ResourceResolutionError",
    "ResourceUpdate",
    "RetryPolicy",
    "SerializedResourceError",
    "SerializedSnapshotBuildError",
    "SerializedSourceFailure",
    "SessionClosedError",
    "Snapshot",
    "SnapshotAcceptanceError",
    "SnapshotAcceptancePolicy",
    "SnapshotAcceptanceReason",
    "SnapshotAcceptanceViolation",
    "SnapshotBuildError",
    "SnapshotBuilder",
    "SnapshotConsistencyError",
    "SnapshotConsistencyPolicy",
    "SnapshotDeadlineExceededError",
    "SnapshotDiagnostics",
    "SnapshotRequest",
    "SnapshotRequirement",
    "SnapshotSession",
    "SnapshotSource",
    "SnapshotValue",
    "SourceAuthorityPolicy",
    "SourceFailure",
    "SourcePayload",
    "SourceProtocolError",
    "SourceQueueTimeoutError",
    "SourceResiliencePolicy",
    "SourceTimeoutError",
    "SourceTimeoutGuarantee",
    "SourceTimeoutGuaranteeStatus",
    "SourceUnavailableError",
    "SubmissionBacklogFullError",
    "SyncResourcePublisher",
    "SyncSnapshotBuilder",
    "SyncSnapshotSession",
    "__version__",
    "capabilities",
    "deepcopy_payload",
    "inspect_source_timeout_guarantee",
    "require_capabilities",
]
